#include "inc/hw_memmap.h"
#include "inc/hw_types.h"
#include "driverlib/gpio.h"
#include "driverlib/sysctl.h"
int main(void)
{
	SysCtlClockSet(SYSCTL_SYSDIV_1|SYSCTL_USE_OSC|SYSCTL_XTAL_8MHZ|SYSCTL_OSC_MAIN);
	SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
	SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOD);
	GPIOPinTypeGPIOInput(GPIO_PORTA_BASE,GPIO_PIN_0);
	GPIOPinTypeGPIOOutput(GPIO_PORTD_BASE,GPIO_PIN_0);//xanh
	GPIOPinTypeGPIOOutput(GPIO_PORTD_BASE,GPIO_PIN_1);//vang
	GPIOPinTypeGPIOOutput(GPIO_PORTD_BASE,GPIO_PIN_2);//do
	GPIOPadConfigSet(GPIO_PORTA_BASE,GPIO_PIN_0,GPIO_STRENGTH_4MA,GPIO_PIN_TYPE_STD_WPU);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_0,0);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_1,0);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_2,0);
while(1)
{
	if(GPIOPinRead(GPIO_PORTA_BASE,GPIO_PIN_0)==0)
	{
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_0,1);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_1,0);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_2,0);
	SysCtlDelay(5*2666666);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_0,0);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_1,2);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_2,0);
	SysCtlDelay(2*2666666);
  GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_0,0);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_1,0);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_2,4);
	SysCtlDelay(7*2666666);
	}
	else
	{
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_0,0);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_1,2);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_2,0);
	SysCtlDelay(1333333);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_0,0);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_1,0);
	GPIOPinWrite(GPIO_PORTD_BASE,GPIO_PIN_2,0);
	SysCtlDelay(1333333);
	}
}
}